In [8]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Using the read_csv function and Path module, created a DataFrame 
# by importing uptown_charlotte_rental_data.csv file 
rental_data_df = pd.read_csv(Path("uptown_charlotte_rental_data.csv")).set_index('Apartment Complex')

#Review the first and last five rows of the DataFrame
display(rental_data_df)

,Unit Type,Availabillity,Rent,SQ.FT,Deposit,Apt Number,Property Value
Apartment Complex,,,,,,,
1010 Dilworth Apartments,1B 1B,9/20/2022,1646,583,0,105,18764.4
1010 Dilworth Apartments,1B 1B,9/22/2022,1570,583,0,217,17898.0
1010 Dilworth Apartments,1B 1B,9/27/2022,1631,583,0,432,18593.4
Alister Uptown,S 1B,9/20/2022,1712,552,0,0,19516.8
Alister Uptown,S 1B,9/5/2022,1776,693,0,0,20246.4
...,...,...,...,...,...,...,...
Uptown Gardens,1B 1B,9/18/2022,1565,794,0,1,17841.0
Uptown Gardens,1B 1B,10/4/2022,1520,794,0,1,17328.0
Uptown Gardens,1B 1B,9/11/2022,1635,774,0,1,18639.0
Uptown Gardens,1B 1B,9/30/2022,1570,774,0,3,17898.0
Uptown Gardens,1B 1B,10/3/2022,1570,774,0,1,17898.0

In [3]:
# Load neighborhoods coordinates data
complex_locations_df = pd.read_csv(Path("apartment_coordinates.csv")).set_index('Apartment Complex')

# Review the DataFrame
display(complex_locations_df)

                                        Lat        Lon
Apartment Complex
1010 Dilworth Apartments          35.210612 -80.840724
500 West Trade                    35.232839 -80.846989
940 Brevard Apartments            35.233797 -80.829731
Alister Uptown                    35.224776 -80.832398
Ascent Uptown Apartments          35.229193 -80.847075
Bell Uptown Charlotte             35.228282 -80.848534
Circa Uptown Apartments           35.230385 -80.850165
Cortland NoDa                     35.240268 -80.822620
Edgeline Flats on Davidson        35.237896 -80.825747
Four One Five Flats               35.236625 -80.840037
Highland Mills Lofts              35.250302 -80.808993
Junction 1504 Luxury Apartments   35.208697 -80.864170
Loft One35 Apartments             35.223234 -80.852482
MAA Enclave                       35.225758 -80.833943
MAA Uptown                        35.234522 -80.844243
Maddox South End                  35.204682 -80.866627
Midtown 205                       35.219830 -80.832672
Park & Kingston Apartments        35.219465 -80.858585
Presley Uptown                    35.217063 -80.840294
Skyhouse Uptown North Apartments  35.233820 -80.837204
Skyhouse Uptown South Apartments  35.233400 -80.838406
Ten 05 West Trade Apartments      35.236555 -80.853598
The Alexander Apartment House     35.257229 -80.836904
The Collective Apartments         35.245376 -80.813461
The Crown of Queen City           35.222603 -80.851882
The Ellis Apartments              35.231297 -80.836775
The Francis Apartments            35.222182 -80.846474
The Julien Apartments             35.222203 -80.809216
The Langston                      35.217823 -80.818822
The Mint 425                      35.231156 -80.846989
The Village at Commonwealth       35.217823 -80.801174
The Vue Charlotte on 5th          35.232909 -80.845273
Uptown 550                        35.220990 -80.844328
Uptown Gardens                    35.235924 -80.843127

In [4]:
# Using the Pandas `concat` function, joined the 
# neighborhood_locations_df and the apartment_list_df DataFrame

apartment_list_df = pd.merge(
    rental_data_df, complex_locations_df,
    left_index= True,
    right_index=True,
    how= 'left',
    sort=False,
    
)
    
# Review the resulting DataFrame
display(apartment_list_df)

,Unit Type,Availabillity,Rent,SQ.FT,Deposit,Apt Number,Property Value,Lat,Lon
Apartment Complex,,,,,,,,,
1010 Dilworth Apartments,1B 1B,9/20/2022,1646,583,0,105,18764.4,35.210612,-80.840724
1010 Dilworth Apartments,1B 1B,9/22/2022,1570,583,0,217,17898.0,35.210612,-80.840724
1010 Dilworth Apartments,1B 1B,9/27/2022,1631,583,0,432,18593.4,35.210612,-80.840724
Alister Uptown,S 1B,9/20/2022,1712,552,0,0,19516.8,35.224776,-80.832398
Alister Uptown,S 1B,9/5/2022,1776,693,0,0,20246.4,35.224776,-80.832398
...,...,...,...,...,...,...,...,...,...
Uptown Gardens,1B 1B,9/18/2022,1565,794,0,1,17841.0,35.235924,-80.843127
Uptown Gardens,1B 1B,10/4/2022,1520,794,0,1,17328.0,35.235924,-80.843127
Uptown Gardens,1B 1B,9/11/2022,1635,774,0,1,18639.0,35.235924,-80.843127
Uptown Gardens,1B 1B,9/30/2022,1570,774,0,3,17898.0,35.235924,-80.843127
Uptown Gardens,1B 1B,10/3/2022,1570,774,0,1,17898.0,35.235924,-80.843127

In [5]:
# Call the dropna function to remove any neighborhoods that do not have data
#apartment_list_df = apartment_list_df.reset_index().dropna()

#Rename the "index" column as "Apartment Complex" for use in the Visualization
apartment_list_df=apartment_list_df.rename(columns={"index": "Apartment Complex"})

# Review the resulting DataFrame
display(apartment_list_df)

,Unit Type,Availabillity,Rent,SQ.FT,Deposit,Apt Number,Property Value,Lat,Lon
Apartment Complex,,,,,,,,,
1010 Dilworth Apartments,1B 1B,9/20/2022,1646,583,0,105,18764.4,35.210612,-80.840724
1010 Dilworth Apartments,1B 1B,9/22/2022,1570,583,0,217,17898.0,35.210612,-80.840724
1010 Dilworth Apartments,1B 1B,9/27/2022,1631,583,0,432,18593.4,35.210612,-80.840724
Alister Uptown,S 1B,9/20/2022,1712,552,0,0,19516.8,35.224776,-80.832398
Alister Uptown,S 1B,9/5/2022,1776,693,0,0,20246.4,35.224776,-80.832398
...,...,...,...,...,...,...,...,...,...
Uptown Gardens,1B 1B,9/18/2022,1565,794,0,1,17841.0,35.235924,-80.843127
Uptown Gardens,1B 1B,10/4/2022,1520,794,0,1,17328.0,35.235924,-80.843127
Uptown Gardens,1B 1B,9/11/2022,1635,774,0,1,18639.0,35.235924,-80.843127
Uptown Gardens,1B 1B,9/30/2022,1570,774,0,3,17898.0,35.235924,-80.843127
Uptown Gardens,1B 1B,10/3/2022,1570,774,0,1,17898.0,35.235924,-80.843127

In [6]:
# Created a plot to analyze neighborhood info
apartment_list_df.hvplot.points(
    x='Lon',
    xlabel= "Longitude",
    y='Lat',
    ylabel= "Latitude",
    geo=True,
    size= 'SQ.FT',
    color= 'Price (mo)',
    frame_width= 700,
    frame_height= 500,
    title= "Uptown Charlotte Available Rental Properties",
    tiles= True,
    hover=True,
    hover_cols=['Unit Type','Apartment Complex','Deposit', 'Apt Number', 'Availabillity'],
    clabel='Rental Price per Month'
)

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (SQ.FT,Unit Type,Apartment Complex,Deposit,Apt Number,Availabillity)

In [7]:
# calculating average rents per apartment complex
avg_rents = apartment_list_df.groupby('Apartment Complex').mean().reset_index()[['Apartment Complex', 'Rent']]
avg_rents['Rent'] = [round(r) for r in avg_rents.Rent] 
avg_rents.sort_values(by=['Rent'], ascending=False, inplace=True)